### ISSUE TITLE
feature request: getting nb object and wt vector from an sfnetworks object

### ISSUE THREAD

**Issue by idshklein** [JosiahParry/sfdep#30]
as [discussed on twitter](https://twitter.com/idoklein1/status/1557719629837094912)  and implemented [in this gist](https://gist.github.com/idshklein/749848c3114760c569c0c6cb05ee141d), sfdep could enjoy a direct access to sfnetworks objects, as they have an easy approach to neighbors and weights.

**Comment by JosiahParry** [comment]
Thanks! A note to self: the var_from_edge works only for undirected graphs where there is a linkage between each node. Need to figure out how to cast edges to undirected

**Comment by JosiahParry** [comment]
https://community.rstudio.com/t/tidygraph-edge-data-as-list-column/145043/2

Answers here

**Comment by JosiahParry** [comment]
One thing to think about is that all of the functionality of sfdep and spdep assume that there is a column that can be used in the same dataset or a vector of the same length. This isn't true for graphs. We may want to evaluate the spatial relationships
Of edge data. In this case the nb list is sort of useless because it is only associated with node data. 

This means that if we want to create local indicators we may have to create methods specifically for tidy graphs

**Comment by JosiahParry** [comment]
There is data stored regarding edges that is not going to be stored in the nodes we can bring them into the node dataset but functions like local_join_count assume a vector which then creates a list from nb object. Whereas in our case we will already have identified the xj observations from our edge data (again, can't be taken from our nodes)

**Comment by JosiahParry** [comment]
see https://github.com/JosiahParry/sfdep/commit/153b28d5a0651e9834dec3f2332f2250ecbbde1e for current work

**Comment by JosiahParry** [comment]
Closed in https://github.com/JosiahParry/sfdep/commit/d5c3f5a2c04dc74b3f873291256eac986731247b.
